### ISSUE TITLE
website field search is broken

### ISSUE THREAD

**Issue by myasonik** [pkbigmarsh/Gen-Con-Buddy-API#5] opened 2024-04-06 22:14 UTC
https://pacific-plains-10689-8ac0e606559a.herokuapp.com/api/events/search?website=discord

But if you look through the data, there are games that have discord URLs

**Comment by pkbigmarsh** [comment] 2024-04-07 15:32
duplicate of #6

**Comment by myasonik** [comment] 2024-04-07 20:08
My bad

The other issues should have said email field, not website 🤦🏼

**Comment by myasonik** [comment] 2024-04-07 20:09
I fixed that one but you should reopen this one

**Comment by pkbigmarsh** [comment] 2024-06-01 16:05
fixed with [17d796a](https://github.com/pkbigmarsh/Gen-Con-Buddy-API/commit/17d796ad44be9b7e625613952923021e8a1757a2)

**Closed as completed by pkbigmarsh** 2024-06-01 16:05 UTC
